### ISSUE TITLE
A possible bug when using HornDroid and AQL-CheckOperator?

### ISSUE THREAD

**Issue by zjbthomas** [FoelliX/CoDiDroid#4]
Hi @FoelliX 

When applying Strategy IV in CoDiDroid's paper, for CHECK, AQL-CheckOperator compared %ANSWERS%, which are two temp_X.xml files created under data/temp/. From the source code of AQL-CheckOperator, I believe it requires the second temp_X.xml file (which is for HornDroid) to have the following permission section so the correct cross-checking can be performed:

```
<permissions>
    <permission>
        <name>HORNDROID_SUCCESSFULLY_EXECUTED</name>
    </permission>
</permissions>
```

Though, when executing HornDroid in AQL-System, if HornDroid has an empty result, its corresponding temp_X.xml generated by AQL-System will not have such permission section. I believe this is a bug leading to CHECK operation cannot discard FP flows in an IntraAppFlows tool like FlowDroid.

I checked HornDroid's answer (an XML file under data/storage/) with the same hash as "Storing part with associated hash" in AQL-System's command line output, and this one has the permission section, so there may be something wrong when converting this file to the temp_X.xml.

You can reproduce the issue by running [ArrayAccess1](https://github.com/secure-software-engineering/DroidBench/blob/master/apk/ArraysAndLists/ArrayAccess1.apk) in DroidBench. **Please enabling -w option for HornDroid as we contacted the authors and it is recommended to make the tool more precise so the results in their paper can be reproduced.** You should see empty results from HornDroid as -w enables precise array element handling.

In addition, when HornDroid produces empty result, AQL-System provides a log saying "Warning: Filtering answer by given Reference returns an empty answer. Trying to ignore app reference." **May I know what this means?**

Thank you in advance!

**Comment by FoelliX** [comment]
Hi @zjbthomas,

> Though, when executing HornDroid in AQL-System, if HornDroid has an empty result, its corresponding temp_X.xml generated by AQL-System will not have such permission section. I believe this is a bug leading to CHECK operation cannot discard FP flows in an IntraAppFlows tool like FlowDroid.

The permission is added by the converter for HornDroid inside the AQL-System (see Line 26-30 in https://github.com/FoelliX/AQL-System/blob/master/src/de/foellix/aql/converter/horndroid/ConverterHD.java). Assumingly, the permission should be added whenever the converter is executed successfully. Whenever its execution fails, e.g. since no tool result was output, it aborts and returns an empty answer (see Line 39).

However, thank you @zjbthomas for making me look at my code again. Just found and fixed a tiny bug with huge effect (see Line -84/+77 in https://github.com/FoelliX/AQL-CheckOperator/commit/5b3678a0c26e06fe2c85781c1917f0d82521a128#diff-a7a09a7d8ff2b948d2b16f22081f7b6894f7616644196919e6b516b626e8c05b). Simply, the wrong answer was parsed. Hence, the whole strategy could never have worked successfully. I will rerun the experiments asap.

To that effect, I just released a new, fixed version of the AQL-CheckOperator (https://github.com/FoelliX/AQL-CheckOperator/releases/tag/0.2.0). The permission check has also been removed, thus, the problems you described should not exist anymore.

> You can reproduce the issue by running ArrayAccess1 in DroidBench. Please enabling -w option for HornDroid as we contacted the authors and it is recommended to make the tool more precise so the results in their paper can be reproduced. You should see empty results from HornDroid as -w enables precise array element handling.

Additionally, I added testcases considering an array access scenario (using HornDroid with and without ``-w``).

> In addition, when HornDroid produces empty result, AQL-System provides a log saying "Warning: Filtering answer by given Reference returns an empty answer. Trying to ignore app reference." May I know what this means?

Do not worry about that message - it does not affect the outcome in this case. The AQL-System's default FILTER operator produces an empty answer, i.e. it removes the permission described above. When there are no flows the whole answer is empty then, hence, the AQL-System tries to filter again in a less accurate way (for more details take a look at the filter methods in https://github.com/FoelliX/AQL-System/blob/master/src/de/foellix/aql/system/DefaultOperatorInstance.java - was implemented initially to deal with combinations of preprocessed and non-preprocessed apps).

Thanks for the feedback!

Cheers,
FoelliX

**Comment by zjbthomas** [comment]
Hi @FoelliX , many thanks for the update and detailed explanation!

Though I believe there is still a tiny bug when HornDroid has empty result. I got the following exception:

```
AQL-System 02/12/2021 - 09:33:55 Process (error): Exception in thread "main" java.lang.NullPointerException
AQL-System 02/12/2021 - 09:33:55 Process (error):       at de.foellix.aql.operator.horndroid.SourceAndSinkEditor.complete(SourceAndSinkEditor.java:40)
AQL-System 02/12/2021 - 09:33:55 Process (error):       at de.foellix.aql.operator.horndroid.CheckOperator.check(CheckOperator.java:70)
AQL-System 02/12/2021 - 09:33:55 Process (error):       at de.foellix.aql.operator.horndroid.CheckOperator.<init>(CheckOperator.java:44)
AQL-System 02/12/2021 - 09:33:55 Process (error):       at de.foellix.aql.operator.horndroid.CheckOperator.main(CheckOperator.java:32)
```

In line 40 of SourceAndSinkEditor.java, `answerHornDroid.getFlows().getFlow()` is run, while `getFlows()` returns null when there is no result.

**Comment by FoelliX** [comment]
Hi @zjbthomas,

could not reproduce since the converter for HornDroid always adds an empty flow element (Line 24 - https://github.com/FoelliX/AQL-System/blob/master/src/de/foellix/aql/converter/horndroid/ConverterHD.java).
However, added some checks to avoid the error you described (https://github.com/FoelliX/AQL-CheckOperator/commit/dbb308dd619365f4f43625bfc436fb80f0b746d4) and made a new release: https://github.com/FoelliX/AQL-CheckOperator/releases/tag/0.2.1

Cheers,
FoelliX

**Comment by zjbthomas** [comment]
Hi @FoelliX , thanks for the fix. I noticed another small bug and I already submitted a pull request for it.

Though, by checking some results, I am a little bit confused about the effect of strategy IV with HornDroid.

As far as I know, results of HornDroid is not in a taint flow format (i.e., for source, it provides no signature and for sink, there is no line number). I notice that CoDiDroid thus marks all flows (**with only sink as HornDroid does not output sources**) in HornDroid with "unknown.pkg.and.Class: unknown.return.Type". Then, you use `SourceAndSinkEditor` to complete HornDroid's flows by matching method names from the given SourcesAndSinks.txt. This is only done for "POTENTIAL LEAK" reported by HornDroid.

In addition, when all flows in HornDroid's results are "NO LEAK", an empty HornDroid xml is generated. In this case, it seems like all flows from the first tool will be discarded (i.e., it is currently not able to check each single flow using HornDroid's information).

As such, can we conclude that strategy IV with HornDroid works like the following:
1. Flows reported by the first tool with sink method name different to those in HornDroid's "POTENTIAL LEAK" will be discarded.
2. If all flows in HornDroid's results are "NO LEAK", then all flows reported by the first tool are discarded. Then we may have FNs.
3. Flows in first tool with sinks that do not reported by HornDroid are also discarded.

Though, I am wondering if the cross-checking should work in another way as HornDroid can make sure the absence of flows. That is to say, we should check "NO LEAK" instead of "POTENTIAL LEAK": for flows reported by the first tool, if the sink method name is the same as those in "NO LEAK", then they should be discarded. (Technically speaking, as HornDroid reports multiple registers for the same sink, "NO LEAK" means for all registers for the same sink, we do not see a "POTENTIAL LEAK".)

For sure, since HornDroid does not distinguish between multiple sink locations with the same method signature, my above idea should also result in over-killed flows, leading to FNs. This requires update of HornDroid or a better tool for cross-checking, as suggested in CoDiDroid's paper.

Please let me know if there is any mistake in my understanding. Thank you for your time!

**Comment by FoelliX** [comment]
Hi @zjbthomas,

> I noticed another small bug and I already submitted a pull request for it.

Thanks for your effort! However, apparently that seems to be *no* bug. This is what you normally get (e.g. by FlowDroid in AQL format for a statement):
````xml
<statementfull>virtualinvoke $r4.&lt;android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)&gt;("+49 1234", null, $r5, null, null)</statementfull>
<statementgeneric>android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)</statementgeneric>
````

So what AQL-CheckOperator generates is:
````xml
<statementfull>&lt;android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)&gt;</statementfull>
<statementgeneric>android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)</statementgeneric>
````

As you can see the statement already looks as similar as possible with "<" (``&lt;``) and ">" (``&gt;``). What is not appearing is the prefix (``virtualinvoke $r4.``) and suffix (``("+49 1234", null, $r5, null, null)``) which cannot be generated on the basis of HornDroid's result.  
**It did not cause any problems apart from not looking similar, right?**

> As such, can we conclude that strategy IV with HornDroid works like the following:

Yes, seems correct.

> Though, I am wondering if the cross-checking should work in another way as HornDroid can make sure the absence of flows. [...] For sure, since HornDroid does not distinguish between multiple sink locations with the same method signature, my above idea should also result in over-killed flows, leading to FNs.

Feel free to give it a try! The more impairing argument against Strategy IV (one way or another) is the runtime of HornDroid, which is very long compared to tools like FlowDroid. With no result (due to timeouts) nothing can be checked.

Cheers,
FoelliX
